import type { NextPage } from 'next'
import Head from 'next/head' 
import { getAllPosts } from '../lib/document'

const Home: NextPage<{posts: {
  [key: string]: string;
}[]}> = ({ posts }) => {
  return (
    <div className="layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        header
      </header>
      <main> 
 
          <h1>{posts[0].title}</h1>
      </main>

      <div/>
      <footer>
        <h2>erhan</h2>
      </footer>
    </div>
  )
}

export default Home


export const getStaticProps = async () => {
  const posts: {
    [key: string]: string;
}[] = await getAllPosts(['title'])

  return {
    props: { posts },
  }
}