import type { NextPage } from "next"
import Head from "next/head"
import Link from "next/link"
import { getAllDocuments } from "../lib/document"
import DocumentType from "../types/document"

const Home: NextPage<{
  documents: DocumentType[]
}> = ({ documents }) => {
  return (
    <div className="layout">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>header</header>
      <main>
        {documents.length > 0 ? (
          documents.map((d, i) => (
            <div key={i}>
              <Link href={d.slug} passHref>
                <a>
                  <h1>
                    {d.order} - {d.title}
                  </h1>
                </a>
              </Link>
              <p>{d.desc}</p>
            </div>
          ))
        ) : (
          <h1>No documents yet.</h1>
        )}
      </main>

      <div />
      <footer>
        <h2>erhan</h2>
      </footer>
    </div>
  )
}

export default Home

export const getStaticProps = async () => {
  const documents: DocumentType[] = await getAllDocuments()

  return {
    props: { documents },
  }
}
